# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Mod\DDA\Resources\ui\BlockMaterial.ui'
#
# Created: Tue May 13 15:57:15 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_BlockMaterial(object):
    def setupUi(self, BlockMaterial):
        BlockMaterial.setObjectName("BlockMaterial")
        BlockMaterial.resize(516, 337)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(51)
        sizePolicy.setVerticalStretch(33)
        sizePolicy.setHeightForWidth(BlockMaterial.sizePolicy().hasHeightForWidth())
        BlockMaterial.setSizePolicy(sizePolicy)
        BlockMaterial.setMinimumSize(QtCore.QSize(516, 337))
        self.verticalLayout = QtGui.QVBoxLayout(BlockMaterial)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(BlockMaterial)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout.addWidget(self.label_9)
        self.weightXSpinB = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightXSpinB.sizePolicy().hasHeightForWidth())
        self.weightXSpinB.setSizePolicy(sizePolicy)
        self.weightXSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.weightXSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.weightXSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightXSpinB.setDecimals(6)
        self.weightXSpinB.setMinimum(-999999999.0)
        self.weightXSpinB.setMaximum(999999999.0)
        self.weightXSpinB.setObjectName("weightXSpinB")
        self.horizontalLayout.addWidget(self.weightXSpinB)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout.addWidget(self.label_10)
        self.weightYSpinB = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weightYSpinB.sizePolicy().hasHeightForWidth())
        self.weightYSpinB.setSizePolicy(sizePolicy)
        self.weightYSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.weightYSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.weightYSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.weightYSpinB.setDecimals(6)
        self.weightYSpinB.setMinimum(-999999999.0)
        self.weightYSpinB.setMaximum(999999999.0)
        self.weightYSpinB.setObjectName("weightYSpinB")
        self.horizontalLayout.addWidget(self.weightYSpinB)
        self.horizontalLayout_7.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(213, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(BlockMaterial)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.stressXSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stressXSpinB.sizePolicy().hasHeightForWidth())
        self.stressXSpinB.setSizePolicy(sizePolicy)
        self.stressXSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.stressXSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stressXSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stressXSpinB.setDecimals(6)
        self.stressXSpinB.setMinimum(-999999999.0)
        self.stressXSpinB.setMaximum(999999999.0)
        self.stressXSpinB.setObjectName("stressXSpinB")
        self.horizontalLayout_3.addWidget(self.stressXSpinB)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.stressYSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stressYSpinB.sizePolicy().hasHeightForWidth())
        self.stressYSpinB.setSizePolicy(sizePolicy)
        self.stressYSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.stressYSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stressYSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stressYSpinB.setDecimals(6)
        self.stressYSpinB.setMinimum(-999999999.0)
        self.stressYSpinB.setMaximum(999999999.0)
        self.stressYSpinB.setObjectName("stressYSpinB")
        self.horizontalLayout_3.addWidget(self.stressYSpinB)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_3.addWidget(self.label_12)
        self.stressXYSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stressXYSpinB.sizePolicy().hasHeightForWidth())
        self.stressXYSpinB.setSizePolicy(sizePolicy)
        self.stressXYSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.stressXYSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stressXYSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stressXYSpinB.setDecimals(6)
        self.stressXYSpinB.setMinimum(-999999999.0)
        self.stressXYSpinB.setMaximum(999999999.0)
        self.stressXYSpinB.setObjectName("stressXYSpinB")
        self.horizontalLayout_3.addWidget(self.stressXYSpinB)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtGui.QSpacerItem(77, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(BlockMaterial)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.speedXSpinB = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedXSpinB.sizePolicy().hasHeightForWidth())
        self.speedXSpinB.setSizePolicy(sizePolicy)
        self.speedXSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.speedXSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.speedXSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedXSpinB.setDecimals(6)
        self.speedXSpinB.setMinimum(-999999999.0)
        self.speedXSpinB.setMaximum(999999999.0)
        self.speedXSpinB.setObjectName("speedXSpinB")
        self.horizontalLayout_2.addWidget(self.speedXSpinB)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.speedYSpinB = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedYSpinB.sizePolicy().hasHeightForWidth())
        self.speedYSpinB.setSizePolicy(sizePolicy)
        self.speedYSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.speedYSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.speedYSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedYSpinB.setDecimals(6)
        self.speedYSpinB.setMinimum(-999999999.0)
        self.speedYSpinB.setMaximum(999999999.0)
        self.speedYSpinB.setObjectName("speedYSpinB")
        self.horizontalLayout_2.addWidget(self.speedYSpinB)
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.speedRSpinB = QtGui.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedRSpinB.sizePolicy().hasHeightForWidth())
        self.speedRSpinB.setSizePolicy(sizePolicy)
        self.speedRSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.speedRSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.speedRSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.speedRSpinB.setDecimals(6)
        self.speedRSpinB.setMinimum(-999999999.0)
        self.speedRSpinB.setMaximum(999999999.0)
        self.speedRSpinB.setObjectName("speedRSpinB")
        self.horizontalLayout_2.addWidget(self.speedRSpinB)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(83, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(BlockMaterial)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.massSpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.massSpinB.sizePolicy().hasHeightForWidth())
        self.massSpinB.setSizePolicy(sizePolicy)
        self.massSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.massSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.massSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.massSpinB.setDecimals(6)
        self.massSpinB.setMinimum(-999999999.0)
        self.massSpinB.setMaximum(999999999.0)
        self.massSpinB.setObjectName("massSpinB")
        self.gridLayout.addWidget(self.massSpinB, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.ElasticitySpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ElasticitySpinB.sizePolicy().hasHeightForWidth())
        self.ElasticitySpinB.setSizePolicy(sizePolicy)
        self.ElasticitySpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.ElasticitySpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.ElasticitySpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ElasticitySpinB.setDecimals(6)
        self.ElasticitySpinB.setMinimum(-999999999.0)
        self.ElasticitySpinB.setMaximum(999999999.0)
        self.ElasticitySpinB.setObjectName("ElasticitySpinB")
        self.gridLayout.addWidget(self.ElasticitySpinB, 0, 3, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 1, 0, 1, 1)
        self.PoissonSpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PoissonSpinB.sizePolicy().hasHeightForWidth())
        self.PoissonSpinB.setSizePolicy(sizePolicy)
        self.PoissonSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.PoissonSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.PoissonSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.PoissonSpinB.setDecimals(6)
        self.PoissonSpinB.setMinimum(-999999999.0)
        self.PoissonSpinB.setMaximum(999999999.0)
        self.PoissonSpinB.setObjectName("PoissonSpinB")
        self.gridLayout.addWidget(self.PoissonSpinB, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 2, 1, 1)
        self.FrictionSpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FrictionSpinB.sizePolicy().hasHeightForWidth())
        self.FrictionSpinB.setSizePolicy(sizePolicy)
        self.FrictionSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.FrictionSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.FrictionSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.FrictionSpinB.setDecimals(6)
        self.FrictionSpinB.setMinimum(-999999999.0)
        self.FrictionSpinB.setMaximum(999999999.0)
        self.FrictionSpinB.setObjectName("FrictionSpinB")
        self.gridLayout.addWidget(self.FrictionSpinB, 1, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.CohesionSpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CohesionSpinB.sizePolicy().hasHeightForWidth())
        self.CohesionSpinB.setSizePolicy(sizePolicy)
        self.CohesionSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.CohesionSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CohesionSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.CohesionSpinB.setDecimals(6)
        self.CohesionSpinB.setMinimum(-999999999.0)
        self.CohesionSpinB.setMaximum(999999999.0)
        self.CohesionSpinB.setObjectName("CohesionSpinB")
        self.gridLayout.addWidget(self.CohesionSpinB, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 2, 1, 1)
        self.extensionSpinB = QtGui.QDoubleSpinBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.extensionSpinB.sizePolicy().hasHeightForWidth())
        self.extensionSpinB.setSizePolicy(sizePolicy)
        self.extensionSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.extensionSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.extensionSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.extensionSpinB.setDecimals(6)
        self.extensionSpinB.setMinimum(-999999999.0)
        self.extensionSpinB.setMaximum(999999999.0)
        self.extensionSpinB.setObjectName("extensionSpinB")
        self.gridLayout.addWidget(self.extensionSpinB, 2, 3, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_4)
        self.buttonBox = QtGui.QDialogButtonBox(BlockMaterial)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.label_9.setBuddy(self.weightXSpinB)
        self.label_10.setBuddy(self.weightYSpinB)
        self.label_5.setBuddy(self.stressXSpinB)
        self.label_6.setBuddy(self.stressYSpinB)
        self.label_12.setBuddy(self.stressXYSpinB)
        self.label_7.setBuddy(self.speedXSpinB)
        self.label_8.setBuddy(self.speedYSpinB)
        self.label_11.setBuddy(self.speedRSpinB)
        self.label.setBuddy(self.massSpinB)
        self.label_2.setBuddy(self.ElasticitySpinB)
        self.label_14.setBuddy(self.PoissonSpinB)
        self.label_3.setBuddy(self.FrictionSpinB)
        self.label_4.setBuddy(self.CohesionSpinB)
        self.label_13.setBuddy(self.extensionSpinB)

        self.retranslateUi(BlockMaterial)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), BlockMaterial.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), BlockMaterial.reject)
        QtCore.QMetaObject.connectSlotsByName(BlockMaterial)

    def retranslateUi(self, BlockMaterial):
        BlockMaterial.setWindowTitle(QtGui.QApplication.translate("BlockMaterial", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("BlockMaterial", "Body Force", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("BlockMaterial", "wx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BlockMaterial", "wy:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("BlockMaterial", "Initial stress", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BlockMaterial", "sx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("BlockMaterial", "sy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("BlockMaterial", "sxy:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("BlockMaterial", "Initial speed", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BlockMaterial", "vx:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("BlockMaterial", "vy:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("BlockMaterial", "vr:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("BlockMaterial", "Rest parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BlockMaterial", "Mass(ma):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BlockMaterial", "Elasticity modulus(em):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("BlockMaterial", "Poisson\'s ratio(pr):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BlockMaterial", "Frictional angle(fa):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BlockMaterial", "Cohesion(co):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("BlockMaterial", "Extension strength(es):", None, QtGui.QApplication.UnicodeUTF8))

