# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Mod\DDA\Resources\ui\DF.ui'
#
# Created: Tue May 13 15:57:15 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(594, 410)
        Dialog.setMinimumSize(QtCore.QSize(594, 410))
        Dialog.setMaximumSize(QtCore.QSize(594, 410))
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.loadDataLabel = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loadDataLabel.sizePolicy().hasHeightForWidth())
        self.loadDataLabel.setSizePolicy(sizePolicy)
        self.loadDataLabel.setMinimumSize(QtCore.QSize(150, 0))
        self.loadDataLabel.setObjectName("loadDataLabel")
        self.gridLayout_2.addWidget(self.loadDataLabel, 0, 1, 1, 1)
        self.btn_ReadData = QtGui.QPushButton(self.groupBox_2)
        self.btn_ReadData.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_ReadData.setObjectName("btn_ReadData")
        self.gridLayout_2.addWidget(self.btn_ReadData, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.loadParasLabel = QtGui.QLabel(self.groupBox_2)
        self.loadParasLabel.setObjectName("loadParasLabel")
        self.gridLayout_2.addWidget(self.loadParasLabel, 1, 1, 1, 1)
        self.btn_ReadPara = QtGui.QPushButton(self.groupBox_2)
        self.btn_ReadPara.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ReadPara.sizePolicy().hasHeightForWidth())
        self.btn_ReadPara.setSizePolicy(sizePolicy)
        self.btn_ReadPara.setMinimumSize(QtCore.QSize(80, 0))
        self.btn_ReadPara.setObjectName("btn_ReadPara")
        self.gridLayout_2.addWidget(self.btn_ReadPara, 1, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.blockNumLineE = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.blockNumLineE.sizePolicy().hasHeightForWidth())
        self.blockNumLineE.setSizePolicy(sizePolicy)
        self.blockNumLineE.setMinimumSize(QtCore.QSize(60, 0))
        self.blockNumLineE.setMaximumSize(QtCore.QSize(70, 16777215))
        self.blockNumLineE.setReadOnly(True)
        self.blockNumLineE.setObjectName("blockNumLineE")
        self.gridLayout_3.addWidget(self.blockNumLineE, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.jointNumLineE = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jointNumLineE.sizePolicy().hasHeightForWidth())
        self.jointNumLineE.setSizePolicy(sizePolicy)
        self.jointNumLineE.setMinimumSize(QtCore.QSize(60, 0))
        self.jointNumLineE.setMaximumSize(QtCore.QSize(70, 16777215))
        self.jointNumLineE.setReadOnly(True)
        self.jointNumLineE.setObjectName("jointNumLineE")
        self.gridLayout_3.addWidget(self.jointNumLineE, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 1, 0, 1, 1)
        self.btn_Config = QtGui.QPushButton(self.groupBox)
        self.btn_Config.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_Config.sizePolicy().hasHeightForWidth())
        self.btn_Config.setSizePolicy(sizePolicy)
        self.btn_Config.setMaximumSize(QtCore.QSize(70, 16777215))
        self.btn_Config.setObjectName("btn_Config")
        self.gridLayout_3.addWidget(self.btn_Config, 1, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.stepsNumSpinB = QtGui.QSpinBox(self.groupBox_3)
        self.stepsNumSpinB.setEnabled(False)
        self.stepsNumSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.stepsNumSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.stepsNumSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.stepsNumSpinB.setMaximum(999999999)
        self.stepsNumSpinB.setObjectName("stepsNumSpinB")
        self.gridLayout.addWidget(self.stepsNumSpinB, 0, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.maxRatioSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.maxRatioSpinB.setEnabled(False)
        self.maxRatioSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.maxRatioSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.maxRatioSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.maxRatioSpinB.setDecimals(6)
        self.maxRatioSpinB.setMinimum(-999999999.0)
        self.maxRatioSpinB.setMaximum(999999999.0)
        self.maxRatioSpinB.setSingleStep(0.0001)
        self.maxRatioSpinB.setProperty("value", 0.0001)
        self.maxRatioSpinB.setObjectName("maxRatioSpinB")
        self.gridLayout.addWidget(self.maxRatioSpinB, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_3)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.timeIntervalSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.timeIntervalSpinB.setEnabled(False)
        self.timeIntervalSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.timeIntervalSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.timeIntervalSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timeIntervalSpinB.setDecimals(6)
        self.timeIntervalSpinB.setMinimum(-999999999.0)
        self.timeIntervalSpinB.setMaximum(999999999.0)
        self.timeIntervalSpinB.setSingleStep(0.01)
        self.timeIntervalSpinB.setObjectName("timeIntervalSpinB")
        self.gridLayout.addWidget(self.timeIntervalSpinB, 1, 3, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 2, 1, 1)
        self.SORSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.SORSpinB.setEnabled(False)
        self.SORSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.SORSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SORSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.SORSpinB.setDecimals(6)
        self.SORSpinB.setMinimum(-999999999.0)
        self.SORSpinB.setMaximum(999999999.0)
        self.SORSpinB.setSingleStep(0.01)
        self.SORSpinB.setObjectName("SORSpinB")
        self.gridLayout.addWidget(self.SORSpinB, 2, 3, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.springStiffnessSpinB = QtGui.QSpinBox(self.groupBox_3)
        self.springStiffnessSpinB.setEnabled(False)
        self.springStiffnessSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.springStiffnessSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.springStiffnessSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.springStiffnessSpinB.setMaximum(9999999)
        self.springStiffnessSpinB.setObjectName("springStiffnessSpinB")
        self.gridLayout.addWidget(self.springStiffnessSpinB, 2, 1, 1, 1)
        self.StaticDynamicSpinB = QtGui.QDoubleSpinBox(self.groupBox_3)
        self.StaticDynamicSpinB.setEnabled(False)
        self.StaticDynamicSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.StaticDynamicSpinB.setMaximumSize(QtCore.QSize(100, 16777215))
        self.StaticDynamicSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.StaticDynamicSpinB.setDecimals(6)
        self.StaticDynamicSpinB.setMinimum(-999999999.0)
        self.StaticDynamicSpinB.setMaximum(1.0)
        self.StaticDynamicSpinB.setSingleStep(0.0001)
        self.StaticDynamicSpinB.setProperty("value", 0.0)
        self.StaticDynamicSpinB.setObjectName("StaticDynamicSpinB")
        self.gridLayout.addWidget(self.StaticDynamicSpinB, 0, 1, 1, 1)
        self.comboBox = QtGui.QComboBox(self.groupBox_3)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 2, 1, 2)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinB_framesInterval = QtGui.QSpinBox(Dialog)
        self.spinB_framesInterval.setMinimumSize(QtCore.QSize(70, 0))
        self.spinB_framesInterval.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinB_framesInterval.setMinimum(1)
        self.spinB_framesInterval.setMaximum(1000)
        self.spinB_framesInterval.setObjectName("spinB_framesInterval")
        self.horizontalLayout.addWidget(self.spinB_framesInterval)
        self.label_13 = QtGui.QLabel(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.comboBox.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "Load Files", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Load Model data status:", None, QtGui.QApplication.UnicodeUTF8))
        self.loadDataLabel.setText(QtGui.QApplication.translate("Dialog", "not load yet", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ReadData.setText(QtGui.QApplication.translate("Dialog", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Load Parameters status(optional):", None, QtGui.QApplication.UnicodeUTF8))
        self.loadParasLabel.setText(QtGui.QApplication.translate("Dialog", "not load yet", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_ReadPara.setText(QtGui.QApplication.translate("Dialog", "load", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "Material parameters", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Block materials number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Joint materials number:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog", "Parameters: ", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_Config.setText(QtGui.QApplication.translate("Dialog", "Configure", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "GroupBox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Statics / Dynamics (0,1):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Max. ratio(.02-.0001):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Max. time interval(0 for auto):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Spring stiffness: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "SOR:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "Frame of axes:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Left Hand", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Right Hand", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "(Earthquake  will be  disabled if left hand)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog", "per steps to store one frame.", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "Real-time display (Only first and last frame will be display if unchecked)", None, QtGui.QApplication.UnicodeUTF8))

