# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\Mod\DDA\Resources\ui\LoadingPointParameters4certainTime.ui'
#
# Created: Tue May 13 15:57:16 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_LoadingPointParameters4certainTime(object):
    def setupUi(self, LoadingPointParameters4certainTime):
        LoadingPointParameters4certainTime.setObjectName("LoadingPointParameters4certainTime")
        LoadingPointParameters4certainTime.resize(350, 152)
        LoadingPointParameters4certainTime.setMinimumSize(QtCore.QSize(350, 152))
        LoadingPointParameters4certainTime.setMaximumSize(QtCore.QSize(350, 152))
        self.buttonBox = QtGui.QDialogButtonBox(LoadingPointParameters4certainTime)
        self.buttonBox.setGeometry(QtCore.QRect(100, 110, 156, 23))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtGui.QWidget(LoadingPointParameters4certainTime)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 20, 291, 74))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.timSpinB = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timSpinB.sizePolicy().hasHeightForWidth())
        self.timSpinB.setSizePolicy(sizePolicy)
        self.timSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.timSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.timSpinB.setDecimals(6)
        self.timSpinB.setMinimum(-999999999.0)
        self.timSpinB.setMaximum(999999999.0)
        self.timSpinB.setObjectName("timSpinB")
        self.gridLayout.addWidget(self.timSpinB, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.horizontalLoadSpinB = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalLoadSpinB.sizePolicy().hasHeightForWidth())
        self.horizontalLoadSpinB.setSizePolicy(sizePolicy)
        self.horizontalLoadSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.horizontalLoadSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.horizontalLoadSpinB.setDecimals(6)
        self.horizontalLoadSpinB.setMinimum(-999999999.0)
        self.horizontalLoadSpinB.setMaximum(999999999.0)
        self.horizontalLoadSpinB.setObjectName("horizontalLoadSpinB")
        self.gridLayout.addWidget(self.horizontalLoadSpinB, 1, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.verticalLoadSpinB = QtGui.QDoubleSpinBox(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.verticalLoadSpinB.sizePolicy().hasHeightForWidth())
        self.verticalLoadSpinB.setSizePolicy(sizePolicy)
        self.verticalLoadSpinB.setMinimumSize(QtCore.QSize(100, 0))
        self.verticalLoadSpinB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.verticalLoadSpinB.setDecimals(6)
        self.verticalLoadSpinB.setMinimum(-999999999.0)
        self.verticalLoadSpinB.setMaximum(999999999.0)
        self.verticalLoadSpinB.setObjectName("verticalLoadSpinB")
        self.gridLayout.addWidget(self.verticalLoadSpinB, 2, 1, 1, 1)

        self.retranslateUi(LoadingPointParameters4certainTime)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), LoadingPointParameters4certainTime.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), LoadingPointParameters4certainTime.reject)
        QtCore.QMetaObject.connectSlotsByName(LoadingPointParameters4certainTime)

    def retranslateUi(self, LoadingPointParameters4certainTime):
        LoadingPointParameters4certainTime.setWindowTitle(QtGui.QApplication.translate("LoadingPointParameters4certainTime", "Loading Point Parameters for certainTime", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("LoadingPointParameters4certainTime", "Time(ti): ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("LoadingPointParameters4certainTime", "Horizontal load(hl):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("LoadingPointParameters4certainTime", "Vertical Load(vl):", None, QtGui.QApplication.UnicodeUTF8))

